broker/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2013,
# Diogo Baeder, Francisco Ciliao, Gabriel Palacio, Ricardo Silva, Vitor George
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modificat-
# ion, are permitted provided that the following conditions are met:
#
#  - Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  - Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
from broker.views import report_facts_complaints, report_total_per_region, \
    report_occurrences_points, report_facts_evolution
from django.conf.urls import patterns, url


urlpatterns = patterns('',
    url(r'report/total-occurrences-per-region/$', report_total_per_region, name='report_total_per_region'),
    url(r'report/occurrences-points/$', report_occurrences_points, name='report_occurrences_points'),
    url(r'report/complaints/$', report_facts_complaints, name='report_facts_complaints'),
    url(r'report/evolution/$', report_facts_evolution, name='report_evolution'),
)

fiscalcidadao/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2013,
# Diogo Baeder, Francisco Ciliao, Gabriel Palacio, Ricardo Silva, Vitor George
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modificat-
# ion, are permitted provided that the following conditions are met:
#
#  - Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  - Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

from broker.api import FactViewSet, OccurrenceViewSet
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import routers

admin.autodiscover()


# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'facts', FactViewSet)
router.register(r'occurrences', OccurrenceViewSet)

urlpatterns = patterns('',
    url(r'^occurrence/$', 'broker.views.post_ocurrence'),
    url(r'', include('broker.urls', namespace='broker')),
    url(r'^api/', include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^occurrences/$', 'website.views.occurrences', name='occurrences'),
    url(r'^$', 'website.views.home'),
    url(r'^select/$', 'website.views.select'),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2013,
# Diogo Baeder, Francisco Ciliao, Gabriel Palacio, Ricardo Silva, Vitor George
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modificat-
# ion, are permitted provided that the following conditions are met:
#
#  - Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  - Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

website/views.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2013,
# Diogo Baeder, Francisco Ciliao, Gabriel Palacio, Ricardo Silva, Vitor George
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modificat-
# ion, are permitted provided that the following conditions are met:
#
#  - Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  - Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

from broker.models import Occurrence
from django.shortcuts import render
from rest_framework import serializers

from broker.models import Occurrence

def home(request):
    return render(request, 'home.html')


def select(request):
    return render(request, 'select-maps.html')


def occurrences(request):
    quantity = 20
    latest = Occurrence.objects.order_by('-date_time')[:quantity]
    return render(request, 'occurrences.html', {'latest': latest})

website/templates/base.html
<!DOCTYPE html>
<html>
{% load bootstrap3 %}
{% load staticfiles %}
  <head>
    <title>Fiscal Cidadão</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    {% bootstrap_css %}
    <!--Leaflet-->
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.ie.css" />
    <![endif]-->
    <link rel="stylesheet" href="{% static 'website/main.css' %}" />
    <script src="//code.jquery.com/jquery.js"></script>
  </head>
  <body>


    {% bootstrap_javascript %}

    <div class="container">

      <!-- Static navbar -->
      <div class="navbar navbar-default">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Fiscal Cidadão</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'occurrences' %}">Ocorrências</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>

      {% block content %}{% endblock %}

    </div> <!-- /container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>
    {% bootstrap_javascript %}
    {% block scripts %}{% endblock %}
  </body>
</html>

website/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h3>Comparação entre áreas da cidade</h3>
        <div class="map" id="region-map"></div>
    </div>
    <div class="col-md-6">
        <h3>Localização dos problemas</h3>
        <div class="map" id="heat-map"></div>
    </div>
</div>

<br/><br/>
<div class=row>
    <div class="col-md-6">
        <div class="" id="fact-chart"></div>
    </div>
    <div class="col-md-6">
        <div id="evolution-chart"></div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'website/heatmap.js' %}"></script>
<script src="{% static 'website/heatmap-leaflet.js' %}"></script>
<script src="//code.highcharts.com/highcharts.js"></script>
<script>
var geoJsonUrl = "{% static 'website/sptrans-areas.geojson' %}",
    occurrenciesPointsUrl = "{% url 'broker:report_occurrences_points' %}",
    totalPerRegionUrl = "{% url 'broker:report_total_per_region' %}",
    factsComplaintsUrl = "{% url 'broker:report_facts_complaints' %}",
    evolutionUrl = "{% url 'broker:report_evolution' %}";

function getColor(d) {
    return d > 80 ? '#FF0000' :
           d > 70  ? '#FF2222' :
           d > 60  ? '#FF4444' :
           d > 50  ? '#FF6666' :
           d > 40   ? '#FF8888' :
           d > 30   ? '#FFAAAA' :
           d > 10   ? '#FFCCCC' :
                      '#FFFFFF';
}

$(document).ready(function(){
    var initialCoordinates = [-23.6725, -46.5995],
        initialZoom = 10,
        regionMap = L.map('region-map').setView(initialCoordinates, initialZoom),
        heatMap = L.map('heat-map').setView(initialCoordinates, initialZoom),
        tileUrl = 'http://{s}.tiles.mapbox.com/v3/examples.map-vyofok3q/{z}/{x}/{y}.png',
        tileConfigs = {
            maxZoom: 18,
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>'
        },
        info = L.control(),
        geojson,
        heatmapLayer,
        generalRegionData,
        legend = L.control({position: 'bottomright'});

    L.tileLayer(tileUrl, tileConfigs).addTo(regionMap);
    L.tileLayer(tileUrl, tileConfigs).addTo(heatMap);

    info.onAdd = function(map) {
        this._div = L.DomUtil.create('div', 'info');
        this.update();
        return this._div;
    };
    info.update = function(properties) {
        this._div.innerHTML = '<h4>Reclamações<br />nos últimos 30 dias</h4>' + (properties ?
            '<strong>Área ' + properties.area + ' ' + properties.nome + ':</strong> '
                + generalRegionData[properties.area] + ' reclamações'
                : 'Passe o mouse nas áreas'
        );
    }


    function style(feature) {
        return {
            weight: 2,
            opacity: 1,
            color: 'white',
            dashArray: '3',
            fillOpacity: 0.7,
            fillColor: getColor(feature.properties.density)
        };
    }

    function highlightFeature(e) {
        var layer = e.target;

        layer.setStyle({
            weight: 5,
            color: '#666',
            dashArray: '',
            fillOpacity: 0.7
        });

        if (!L.Browser.ie && !L.Browser.opera) {
            layer.bringToFront();
        }

        info.update(layer.feature.properties);
    }

    function resetHighlight(e) {
        geojson.resetStyle(e.target);
        info.update();
    }

    function zoomToFeature(e) {
        regionMap.fitBounds(e.target.getBounds());
    }

    function onEachFeature(feature, layer) {
        layer.on({
            mouseover: highlightFeature,
            mouseout: resetHighlight,
            click: zoomToFeature
        });
    }

    heatmapLayer = L.TileLayer.heatMap({
        radius: 5,
        opacity: 0.8,
        gradient: {
            0.45: "rgb(0,0,255)",
            0.55: "rgb(0,255,255)",
            0.65: "rgb(0,255,0)",
            0.95: "yellow",
            1.0: "rgb(255,0,0)"
        }
    });

    legend.onAdd = function (map) {

        var div = L.DomUtil.create('div', 'info legend'),
            grades = [0, 10, 30, 40, 50, 60, 70, 80],
            labels = [],
            from, to;

        for (var i = 0; i < grades.length; i++) {
            from = grades[i];
            to = grades[i + 1];

            labels.push(
                '<i style="background:' + getColor(from + 1) + '"></i> ' +
                from + (to ? '&ndash;' + to : '+'));
        }

        div.innerHTML = labels.join('<br>');
        return div;
    };

    $.getJSON(geoJsonUrl, function(geoJsonData){
        $.getJSON(totalPerRegionUrl, function(regionData){
            generalRegionData = regionData;
            geojson = L.geoJson(geoJsonData, {
                'style': function(feature){
                    var regionDensity = regionData[feature.properties.area];

                    return {
                        'fillColor': getColor(regionDensity),
                        'fillOpacity': 0.8,
                        'stroke': false
                    }
                },
                'onEachFeature': onEachFeature
            }).addTo(regionMap);
            info.addTo(regionMap);
            legend.addTo(regionMap);
        });
    });

    $.getJSON(occurrenciesPointsUrl, function(data){
        heatmapLayer.addData(data);
        heatmapLayer.addTo(heatMap);
    });

    $.getJSON(evolutionUrl, function(data){
        $('#evolution-chart').highcharts({
            chart: {
                type: 'area'
            },
            title: {
                text: 'Evolução dos problemas'
            },
            xAxis: {
                categories: ['4 meses', '3 meses', '2 meses', '1 mês'],
                tickmarkPlacement: 'on',
                title: {
                    enabled: false
                }
            },
            yAxis: {
                title: {
                    text: 'Porcentagem'
                }
            },
            tooltip: {
                pointFormat: '<span style="color:{series.color}">{series.name}</span>: ({point.y:,.0f} )<br/>',
                shared: true
            },
            plotOptions: {
                area: {
                    stacking: 'normal',
                    lineColor: '#ffffff',
                    lineWidth: 1,
                    marker: {
                        lineWidth: 1,
                        lineColor: '#ffffff'
                    }
                }
            },
            series: data
        });

    });


    $.getJSON(factsComplaintsUrl, function(data){
        Highcharts.getOptions().colors = Highcharts.map(Highcharts.getOptions().colors, function(color) {
            return {
                radialGradient: { cx: 0.5, cy: 0.3, r: 0.7 },
                stops: [
                    [0, color],
                    [1, Highcharts.Color(color).brighten(-0.3).get('rgb')] // darken
                ]
            };
        });
        $('#fact-chart').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'Distribuição dos problemas'
            },
            subtitle: {
                text: "Últimos 30 dias"
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false,
                    },
                    showInLegend: true
                }
            },
            series: [{
                type: 'pie',
                name: 'Reclamações',
                data: data
            }]
        });
    });
});
</script>
{% endblock %}

website/templates/occurrences.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<h1>Últimas ocorrências</h1>
<table class="table">
    <thead>
        <tr>
            <th>Fato</th>
            <th>Data e hora</th>
            <th>Linha</th>
        </tr>
    </thead>
    <tbody>
    {% for occurrence in latest %}
        <tr>
            <td>{{ occurrence.fact }}</td>
            <td>{{ occurrence.date_time }}</td>
            <td>{{ occurrence.route }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

website/templates/select-maps.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <title>Drag Feature Example</title>
        
        <link rel="stylesheet" href="http://openlayers.org/dev/examples/style.css" type="text/css">
        <link rel="stylesheet" href="style.css" type="text/css">
        <style type="text/css">
            #controls {
                width: 512px;
            }
            #controlToggle {
                padding-left: 1em;
            }
            #controlToggle li {
                list-style: none;
            }
        </style>

        <script src="http://openlayers.org/api/2.11/OpenLayers.js"></script>
        <script type="text/javascript">
            var map, vectors, controls;
            function init(){
                map = new OpenLayers.Map('map');
                var wms = new OpenLayers.Layer.WMS( "OpenLayers WMS",
                    "http://vmap0.tiles.osgeo.org/wms/vmap0?", {layers: 'basic'});
    
                // allow testing of specific renderers via "?renderer=Canvas", etc
                var renderer = OpenLayers.Util.getParameters(window.location.href).renderer;
                renderer = (renderer) ? [renderer] : OpenLayers.Layer.Vector.prototype.renderers;

                vectors = new OpenLayers.Layer.Vector("Vector Layer", {
                    renderers: renderer
                });

                map.addLayers([wms, vectors]);
                map.addControl(new OpenLayers.Control.LayerSwitcher());
                map.addControl(new OpenLayers.Control.MousePosition());

                controls = {
                    point: new OpenLayers.Control.DrawFeature(vectors,
                                OpenLayers.Handler.Point),
                    line: new OpenLayers.Control.DrawFeature(vectors,
                                OpenLayers.Handler.Path),
                    polygon: new OpenLayers.Control.DrawFeature(vectors,
                                OpenLayers.Handler.Polygon),
                    drag: new OpenLayers.Control.DragFeature(vectors)
                };

                for(var key in controls) {
                    map.addControl(controls[key]);
                }

                map.setCenter(new OpenLayers.LonLat(0, 0), 3);
                document.getElementById('noneToggle').checked = true;
            }

            function toggleControl(element) {
                for(key in controls) {
                    var control = controls[key];
                    if(element.value == key && element.checked) {
                        control.activate();
                    } else {
                        control.deactivate();
                    }
                }
            }
        </script>
    </head>
    <body onload="init()">
        <h1 id="title">Drag Feature Example</h1>

        <div id="tags">
            point, line, linestring, polygon, digitizing, geometry, draw, drag
        </div>

        <p id="shortdesc">
            Demonstrates point, line and polygon creation and editing.
        </p>

        <div id="map" class="smallmap"></div>
        
        <div id="controls">
            <ul id="controlToggle">
                <li>
                    <input type="radio" name="type" value="none" id="noneToggle"
                           onclick="toggleControl(this);" checked="checked" />
                    <label for="noneToggle">navigate</label>
                </li>
                <li>
                    <input type="radio" name="type" value="point" id="pointToggle" onclick="toggleControl(this);" />
                    <label for="pointToggle">draw point</label>
                </li>
                <li>
                    <input type="radio" name="type" value="line" id="lineToggle" onclick="toggleControl(this);" />
                    <label for="lineToggle">draw line</label>
                </li>
                <li>
                    <input type="radio" name="type" value="polygon" id="polygonToggle" onclick="toggleControl(this);" />
                    <label for="polygonToggle">draw polygon</label>
                </li>
                <li>
                    <input type="radio" name="type" value="drag" id="dragToggle"
                           onclick="toggleControl(this);" />
                    <label for="dragToggle">drag feature</label>
                </li>
            </ul>
        </div>

        <div id="docs"></div>
    </body>
</html>